### Linear Algebra with Scipy

In [49]:
import numpy as np
import scipy.linalg as la

In [50]:
a = ([1,2,3,4,5])

In [51]:
a

[1, 2, 3, 4, 5]

In [52]:
#a.ndim

In [53]:
#a.shape

In [54]:
#a.size

### Two dimentional array is a matrix

In [55]:
M = np.array([[1,2],[3,7],[-1,5]])
print(M)

[[ 1  2]
 [ 3  7]
 [-1  5]]


In [56]:
M.ndim

2

In [57]:
M.shape

(3, 2)

In [58]:
M.size

6

In [59]:
col = M[:,0] 
print(col)

[ 1  3 -1]


In [60]:
col.ndim

1

In [61]:
col.size

3

In [62]:
col.shape

(3,)

In [63]:
print(col)

[ 1  3 -1]


In [64]:
column = np.array([2,7,5]).reshape(3,1)
print(column)

[[2]
 [7]
 [5]]


In [65]:
print('Dimensions:', column.ndim)
print('Shape:', column.shape)
print('Size:', column.size)

Dimensions: 2
Shape: (3, 1)
Size: 3


### Matrix Operations and functions

In [68]:
M = np.array([[1,2,3], [4,5,6]])
print(M)

[[1 2 3]
 [4 5 6]]


In [70]:
M1 = M*M
M1

array([[ 1,  4,  9],
       [16, 25, 36]])

### Matrix multiplication

In [75]:
matrix_1 = [[1,2,3], [4,5,6], [7,8,9]]
matrix_2 = [[7,8,9], [4,5,6], [1,2,3]]

In [76]:
matrix_1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [77]:
matrix_2

[[7, 8, 9], [4, 5, 6], [1, 2, 3]]

In [80]:
result = np.dot(matrix_1,matrix_2)
result

array([[ 18,  24,  30],
       [ 54,  69,  84],
       [ 90, 114, 138]])