### Numpy array attributes

In [15]:
import numpy as np

In [31]:
np.random.seed(0)       # seed is for reproducibility
x1 = np.random.randint(10, size=7)

In [32]:
x1

array([5, 0, 3, 3, 7, 9, 3])

In [33]:
x1

array([5, 0, 3, 3, 7, 9, 3])

In [23]:
x1

array([5, 0, 3, 3, 7, 9, 3])

In [24]:
x2 = np.random.randint(10, size=(3, 4))

In [25]:
x2

array([[5, 2, 4, 7],
       [6, 8, 8, 1],
       [6, 7, 7, 8]])

In [26]:
x2

array([[5, 2, 4, 7],
       [6, 8, 8, 1],
       [6, 7, 7, 8]])

In [27]:
x2

array([[5, 2, 4, 7],
       [6, 8, 8, 1],
       [6, 7, 7, 8]])

In [37]:
x3 = np.random.randint(10, size=(3, 4, 5))

In [38]:
x3

array([[[5, 0, 1, 5, 9],
        [3, 0, 5, 0, 1],
        [2, 4, 2, 0, 3],
        [2, 0, 7, 5, 9]],

       [[0, 2, 7, 2, 9],
        [2, 3, 3, 2, 3],
        [4, 1, 2, 9, 1],
        [4, 6, 8, 2, 3]],

       [[0, 0, 6, 0, 6],
        [3, 3, 8, 8, 8],
        [2, 3, 2, 0, 8],
        [8, 3, 8, 2, 8]]])

In [39]:
x3

array([[[5, 0, 1, 5, 9],
        [3, 0, 5, 0, 1],
        [2, 4, 2, 0, 3],
        [2, 0, 7, 5, 9]],

       [[0, 2, 7, 2, 9],
        [2, 3, 3, 2, 3],
        [4, 1, 2, 9, 1],
        [4, 6, 8, 2, 3]],

       [[0, 0, 6, 0, 6],
        [3, 3, 8, 8, 8],
        [2, 3, 2, 0, 8],
        [8, 3, 8, 2, 8]]])