Product calculation (Traversal method)

In [350]:
def multiplylist(mylist):# web
    result = 1
    for i in mylist:  # Why we dont need here x in range?
        result = result*i
    return result

In [351]:
L1 = [1,2,3]
print(multiplylist(L1))

6


In [352]:
L2 = [5,6,7]
print(multiplylist(L2))

210


In [353]:
def myproduct(p): # myself
    product = 1
    for i in p:
        product = product*i
    return product

In [354]:
p = [100, 5, 10]
print(myproduct(p))

5000


Product calculation using numpy.prod()

In [355]:
L = [i for i in range(1,5)]

In [356]:
L

[1, 2, 3, 4]

In [357]:
import numpy as np 
L = [i for i in range(1,5)]
result1 = np.prod(L)
print(result1)

24


Calcualtion of the sum

In [358]:
total = 0
for i in range(1,101):
    total = total + i

In [359]:
total

5050

In [360]:
def sum(S):
    sum = 0
    for i in range(1,101):
        sum = sum + i
    return sum
    

In [361]:
sum(100)

5050

In [362]:
Alu = [i for i in range(1,101)]
sum(Alu)

5050

factorial calculation

In [363]:
def factorial(n):
    product = 1
    while n > 0:
        product = product*n
        n = n-1
    return product

In [364]:
factorial(6)

720

In [365]:
import numpy as np

In [366]:
np .pi

3.141592653589793

In [367]:
def area(r):
    area = np.pi*r*r
    return area


In [368]:
area(5)

78.53981633974483

In [369]:
def circumference(r):
    circumference = 2*np.pi*r
    return circumference

In [370]:
circumference(5)

31.41592653589793

In [371]:
def volrec(l,b,h):
    volume = l*b*h
    return volume

In [372]:
volrec(2,3,5)

30

In [373]:
def factorialr(n):   # Recursive                   
    if n == 0:
        return 1
    elif n == 1:
        return 1
    
    return n*factorialr(n-1)

In [374]:
factorialr(5)

120

In [375]:
import random as r

In [376]:
r. randint(1,6)

5

In [377]:
def dice(n):
    L = []
    for i in range(n):
        face = r.randint(1,6)
        L.append(face)
    return L

In [378]:
dice(5)

[5, 5, 2, 1, 3]

In [379]:
L1 = dice(5)
L2 = dice(5)

In [380]:
L1

[5, 3, 3, 1, 2]

In [381]:
L2

[5, 6, 5, 3, 6]

In [382]:
for d1,d2 in  zip(L1,L2):
    print(d1,d2,d1+d2)

5 5 10
3 6 9
3 5 8
1 3 4
2 6 8


In [383]:
def count(L1,L2,p,q):
    c = 0
    for l1,l2 in zip(L1,L2):
        c = c+1
    return c

In [384]:
np.zeros((6,6), dtype = int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [385]:
N = 500 # why got the same element in the matrix
L1 = dice(N)
L2 = dice(N)
A = np.zeros((6,6), dtype = int)
for i in range(6):
    for j in range(6):
        A[i,j] = count(L1,L2,i+1,j+1)

In [386]:
A

array([[500, 500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500, 500]])

### print function

In [387]:
print("Hello", "how are you?", sep="---")

Hello---how are you?


### np.ones
It makes as array of 1

In [388]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [389]:
np.ones(5, int)

array([1, 1, 1, 1, 1])

In [390]:
np.ones(2,int)

array([1, 1])

In [391]:
np.ones((5,2),int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [392]:
s=(5,2)
np.ones(s, int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [393]:
np.random.random()

0.33850393076655816

In [394]:
np.empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [395]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [396]:
np.arange(10,25,5)

array([10, 15, 20])

In [397]:
np.random.random((2,2))

array([[0.65612059, 0.40998863],
       [0.21669303, 0.58234862]])

In [398]:
np.zeros((3,4,5),dtype=np.int16)

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=int16)

In [399]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [400]:
np.eye((10))

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [401]:
 np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [402]:
np.random.choice(10, 5)

array([6, 6, 2, 9, 8])

In [403]:
import numpy as np

In [404]:
a = np.arange(15).reshape(3,5)

In [405]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [406]:
a.shape

(3, 5)

In [407]:
a.ndim

2

In [408]:
type(a)

numpy.ndarray

In [409]:
a.dtype.name

'int32'

In [410]:
a.itemsize

4

In [411]:
a.size

15

In [412]:
np.ones( (2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [413]:
import pandas as pd

In [414]:
pd.Series([2, 1, 3, 4, 8, 9, 5, 4, 3, 2, 1]).unique()

array([2, 1, 3, 4, 8, 9, 5], dtype=int64)

### Function

In [415]:
def my_function():
    print("Hello from a function")
my_function()

Hello from a function


In [416]:
def first_name(fname):
    print(fname + " Panday")

### Arguments

In [417]:
first_name("Namuna")
first_name("Popular")
first_name("Ramesh")

Namuna Panday
Popular Panday
Ramesh Panday


### Number of Arguments

In [418]:
def name(fname, lname):
    print(fname + " " + lname)

In [419]:
name("Namuna", "Panday")
name("Dibakar", "Sigdel")
name("Arya", "Sigdel")

Namuna Panday
Dibakar Sigdel
Arya Sigdel


### Arbitrary Arguments, *args

In [420]:
def my_family(*kids):
    print("The youngest child is " + kids[1])

In [421]:
my_family("Arya", "Nirakar", "Niharika")

The youngest child is Nirakar


### Keyword Arguments

In [426]:
def my_family(child1, child2, child3):
    print("The youngest child is " + child3)

In [427]:
my_family(child1="Arya", child2="Niharika", child3="Priya")

The youngest child is Priya


### Arbitrary Keyword Arguments, **kwargs

In [434]:
def my_family(**kid):
    print("Her First name is "+ kid["fname"])

In [435]:
my_family(fname = "Namuna", lname ="Panday")

Her First name is Namuna


### Deafult Parameters Value

In [437]:
def my_country(country = "Nepal"):
    print("I am from "+ country)

In [438]:
my_country(country = "USA")
my_country(country = "Japan")
my_country(country = "UK")
my_country()

I am from USA
I am from Japan
I am from UK
I am from Nepal


### Passing a list as an arguments

In [448]:
def my_function(x):
    for i in x:
        print(i)

In [449]:
food = ["apple", "banana", "cherry"]
my_function(food)

apple
banana
cherry


In [450]:
friend = ["Ram", "Shyam", "Hari", "Gita"]
my_function(friend)

Ram
Shyam
Hari
Gita


### Return values

In [451]:
def my_function(x):
    return 5*x

In [455]:
my_function(2)

10

### Recursion Function

In [459]:
def my_recursive(f):
    if f>0:
        result = f + my_recursive(f-1)
        print(result)
    else:
        result = 0
    return result
my_recursive(5)


1
3
6
10
15


15

### Calculate factorial by recursive method

In [465]:
def my_factorial(k):
    if k>1:
        result = k*my_factorial(k-1)
        #print(result)
    else:
        result = 1
    return result
my_factorial(5)

120